# This is the configuration file for Netlify.
# It tells Netlify how to build and deploy your site.

[build]
  # This tells Netlify that your website's files are inside the "creators-hub" folder.
  publish = "creators-hub"

# This section tells Netlify where to find your serverless functions.
[functions]
  directory = "netlify/functions/"

# This section sets up a rule for Single Page Applications (SPAs) like ours.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
